# Generated by Django 4.0.1 on 2022-01-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=120, null=True)),
                ('taskDesc', models.CharField(max_length=10, null=True)),
                ('taskPriority', models.CharField(max_length=10, null=True)),
                ('taskStatus', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
