# Generated by Django 4.0.1 on 2022-01-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0002_user_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
