# Generated by Django 4.0.1 on 2022-01-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0008_alter_events_desc_alter_events_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskPriority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Super important', 'Super Important')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskStatus',
            field=models.CharField(choices=[('To do', 'To do'), ('In progess', 'In progess'), ('Done', 'Done')], max_length=20, null=True),
        ),
    ]
