# Generated by Django 4.0.1 on 2022-01-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0009_alter_events_endtime_alter_events_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskPriority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Super important', 'Super Important')], default=('Low', 'Low'), max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskStatus',
            field=models.CharField(choices=[('To do', 'To do'), ('In progess', 'In progess'), ('Done', 'Done')], default=('In progess', 'In progess'), max_length=20),
        ),
    ]
