# Generated by Django 4.0.1 on 2022-01-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0010_alter_task_taskpriority_alter_task_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskPriority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Super important', 'Super Important')], default=('Medium', 'Medium'), max_length=20),
        ),
    ]
