# Generated by Django 4.0.1 on 2022-01-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0011_alter_task_taskpriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskStatus',
            field=models.CharField(choices=[('To do', 'To do'), ('In progess', 'In progess'), ('Done', 'Done')], default=('To do', 'To do'), max_length=20),
        ),
    ]
