# Generated by Django 4.0.1 on 2022-01-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0012_alter_task_taskstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
