# Generated by Django 4.0.1 on 2022-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0014_userdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskPriority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskName',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskDesc',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
