# Generated by Django 4.0.1 on 2022-01-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0015_rename_taskpriority_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Done', 'Done')], default=('To do', 'To do'), max_length=20),
        ),
    ]
